<?php

/**
 * @file
 * Contains outside_in.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function outside_in_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the outside_in module.
    case 'help.page.outside_in':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function outside_in_theme() {
  return [
    'outside_in' => [
      'render element' => 'children',
    ],
  ];
}
